### PR TITLE
Merge installation scripts into main from webapp

### PR DESCRIPTION
**Pull request by timvdlee**
After the installation we are going to check if changes are required if they are not. This PR can be merged with main.

### CODE REVIEW

**Comment by Timmerman73** [comment]
We also fixed the unit tests because they did not have access to the enviroment variable which defines the database file.

**Review by ifokkema — COMMENTED** [review]
Why set the `database_json_file` key in every function, not once per file? I can imagine importing it from elsewhere will be more difficult, but once per file should work, no?

**Comment by Timmerman73** [comment]
> Why set the `database_json_file` key in every function, not once per file? I can imagine importing it from elsewhere will be more difficult, but once per file should work, no?

I misunderstood how pytest handled enviroment variables. but after testing this seems to work so we changed it.

**Comment by Timmerman73** [comment]
A miscommunication happened we had quickly had to add a feature so files with sslp information can have a different population per row.
Everything should now be done and the PR is ready for review.

**Comment by ifokkema** [comment]
I couldn't find documentation on the reason for the `_backup.bat` scripts introduced in 1ed6c917eb637b829679415725ce21222932354a. I actually can't find any documentation at all, so I assume it hasn't been added to git?

**Pull request merged**
